<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class PayPesaPal extends CI_Controller {

	/**
	 * Core CMS controller 
	 * For Setting Purpose Purpose
	 * @see https://codeigniter.com/user_guide/general/controllers.html
	 */

    private $TXNtable = 'pesapal_txn'; //TXN Table

    public function __construct(){

        parent::__construct();

        //Libraries
        $this->load->database();
        $this->load->library('pesapal');
        $this->load->library('form_validation');

        //Helpers

        //Models
    }

    public function index()
    {
        $this->load->view('pesapal/index');
    }

    //Receive Data
   	public function buyproducts()
   	{
   		$this->form_validation->set_rules('firstname', 'First Name', 'trim|required|min_length[5]|max_length[12]');
   		$this->form_validation->set_rules('lastname', 'Last Name', 'trim|required|min_length[5]|max_length[12]');
   		$this->form_validation->set_rules('email', 'Email', 'trim|required|min_length[5]|max_length[50]');
   		$this->form_validation->set_rules('mobile', 'Mobile', 'trim|required|min_length[5]|max_length[15]');
   		$this->form_validation->set_rules('amount', 'Amount', 'trim|required|min_length[1]|max_length[22]');

		//If There is error return and show
		if ($this->form_validation->run() == FALSE) {

        	$this->load->view('pesapal/index');
		}else{


			//Data
			$fname = $this->db->escape_str($this->input->post('firstname'));
			$lname = $this->db->escape_str($this->input->post('lastname'));

			$email = $this->db->escape_str($this->input->post('email'));
			$mobile = $this->db->escape_str($this->input->post('mobile'));
			$amount = $this->db->escape_str($this->input->post('amount'));

			$description = 'Product Purchased';
			$type = 'MERCHANT';
			$product = rand(); //unique order id of the transaction, generated by merchant

			//Pay To PesaPal
			$this->paynow($fname,$lname,$email,$mobile,$amount,$description,$type,$product);
		}

   	}

   	//PayNow
	public function paynow($fname,$lname,$email,$mobile,$amount,$description,$type,$order_id)
	{
		$token = $params = NULL;
		$consumer_key = 'Your PesaPal Merchant Consumer Key';
		$consumer_secret = 'Your PesaPal Merchant Consumer Secret';
		$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
		$iframelink = 'https://demo.pesapal.com/api/PostPesapalDirectOrderV4';//change to      
		                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!
		
		//Get form details <br>
		$amount = $amount;
		$amount = number_format($amount, 2);//format amount to 2 decimal places
		$desc = $description;
		$type = $type; //default value = MERCHANT
		$reference = $order_id;//$_POST['reference'];//unique order id of the transaction, generated by merchant
		$first_name = $fname; //[optional]
		$last_name = $lname; //[optional]
		$email = '';
		$phonenumber = $mobile; //ONE of email or phonenumber is required

		$callback_url = 'https://www.yourhost.com/pesapal/paid'; //redirect url, the page that will handle the response from pesapal.
		$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchemainstance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
		$post_xml = htmlentities($post_xml);

		$consumer = new OAuthConsumer($consumer_key, $consumer_secret);
		//post transaction to pesapal
		$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET",
		$iframelink, $params);
		$iframe_src->set_parameter("oauth_callback", $callback_url);
		$iframe_src->set_parameter("pesapal_request_data", $post_xml);
		$iframe_src->sign_request($signature_method, $consumer, $token);

		$data['iframe_src'] = $iframe_src;

		//View
        $this->load->view('pesapal/paynow',$data);
    }

    //Paid To PesaPal
    public function paid()
    {
    	//Date and Time
		date_default_timezone_set('Africa/Nairobi');
		$dateTime =  date('Y-m-d, H:i:s');

    	//Values
		$reference = null;
		$pesapal_tracking_id = null;

		if(isset($_GET['pesapal_merchant_reference'])) {

			$reference = $_GET['pesapal_merchant_reference'];
		}

		if(isset($_GET['pesapal_transaction_tracking_id'])){

			$pesapal_tracking_id = $_GET['pesapal_transaction_tracking_id'];
		}

		//store $pesapal_tracking_id in your database against the order with orderid = $reference
		$payment_status = array(
			'reference_code' =>$reference,
			'tracking_id' =>$pesapal_tracking_id,
			'txn_date' =>$dateTime,
			'txn_status' =>'WAITING'
		);

		//Insert
		$this->db->insert($this->TXNtable, $payment_status);

		//Index
		$this->success();
    }

    //Paid Successful -> IPN
    public function ipn()
    {

		$consumer_key="Your PesaPal Merchant Consumer Key";//Register a merchant account on
		                   //demo.pesapal.com and use the merchant key for testing.
		                   //When you are ready to go live make sure you change the key to the live account
		                   //registered on www.pesapal.com!
		$consumer_secret="Your PesaPal Merchant Consumer Secret";// Use the secret from your test
		                   //account on demo.pesapal.com. When you are ready to go live make sure you 
		                   //change the secret to the live account registered on www.pesapal.com!
		$statusrequestAPI = 'https://demo.pesapal.com/api/querypaymentstatus';//change to      
		                   //https://www.pesapal.com/api/querypaymentstatus' when you are ready to go live!

		// Parameters sent to you by PesaPal IPN
		$pesapalNotification=$_GET['pesapal_notification_type'];
		$pesapalTrackingId=$_GET['pesapal_transaction_tracking_id'];
		$pesapal_merchant_reference=$_GET['pesapal_merchant_reference'];

		if($pesapalNotification=="CHANGE" && $pesapalTrackingId!='')
		{
			$token = $params = NULL;
			$consumer = new OAuthConsumer($consumer_key, $consumer_secret);
			$signature_method = new OAuthSignatureMethod_HMAC_SHA1();

			//get transaction status
			$request_status = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $statusrequestAPI, $params);
			$request_status->set_parameter("pesapal_merchant_reference", $pesapal_merchant_reference);
			$request_status->set_parameter("pesapal_transaction_tracking_id",$pesapalTrackingId);
			$request_status->sign_request($signature_method, $consumer, $token);

			$ch = curl_init();
			curl_setopt($ch, CURLOPT_URL, $request_status);
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_HEADER, 1);
			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
			if(defined('CURL_PROXY_REQUIRED')) if (CURL_PROXY_REQUIRED == 'True')
			{
			$proxy_tunnel_flag = (defined('CURL_PROXY_TUNNEL_FLAG') && strtoupper(CURL_PROXY_TUNNEL_FLAG) == 'FALSE') ? false : true;
			curl_setopt ($ch, CURLOPT_HTTPPROXYTUNNEL, $proxy_tunnel_flag);
			curl_setopt ($ch, CURLOPT_PROXYTYPE, CURLPROXY_HTTP);
			curl_setopt ($ch, CURLOPT_PROXY, CURL_PROXY_SERVER_DETAILS);
			}

			$response = curl_exec($ch);
			$header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
			$raw_header  = substr($response, 0, $header_size - 4);
			$headerArray = explode("\r\n\r\n", $raw_header);
			$header      = $headerArray[count($headerArray) - 1];

			//transaction status
			$elements = preg_split("/=/",substr($response, $header_size));
			$status = $elements[1];

			curl_close ($ch);

			//UPDATE YOUR DB TABLE WITH NEW STATUS FOR TRANSACTION WITH pesapal_transaction_tracking_id $pesapalTrackingId
			//Date and Time
			date_default_timezone_set('Africa/Nairobi');
			$dateTime =  date('Y-m-d, H:i:s');

			//Update
			$payment_updates = array(
			'tracking_id' =>$pesapalTrackingId,
			'txn_ipn_date' =>$dateTime,
			'notification_type' =>$status,
			'txn_status' =>'PAID',
			'flag' =>1
			);

			$this->db->where('reference_code', $pesapal_merchant_reference);
			$this->db->update($this->TXNtable, $payment_updates);

			$result = $resp.' | '.$status;

			if($this->db->affected_rows() > 0 && $status != "PENDING")
			{
			$resp="pesapal_notification_type=$pesapalNotification&pesapal_transaction_tracking_id=$pesapalTrackingId&pesapal_merchant_reference=$pesapal_merchant_reference";
			ob_start();
			echo $resp;
			ob_flush();
			exit;
			}
		}
    }

    //Transaction Success
    public function success()
    {
    	$data['response'] = 'Successful';

		//View
        $this->load->view('pesapal/status',$data);
    }

    //Transaction Failed
    public function failed()
    {
    	$data['response'] = 'Failed';

		//View
        $this->load->view('pesapal/status',$data);
    }

    //Transaction Feedback
    public function feedback($resp)
    {
    	$data['response'] = $resp;

		//View
        $this->load->view('pesapal/feedback',$data);
    }

}

/* End of file PayPesaPal.php */
/* Location: ./application/controllers/PayPesaPal.php */